### ISSUE TITLE
Ignore files that should not be packaged. 

### ISSUE THREAD

**Issue by jonathan-s** [phantomcyber/dev-cicd-tools#81]
In the documentation there is the following line. https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/Tutorial#Compile_and_install_the_app

> When compiling the app, ignore the files specified in the ignore file. The default ignore file is `.compile_app.ignore`. 

I was hoping that I would be able to ignore files that should not be packaged using that file, and thus not trigger the following error in static tests 

```
            {
                "product_name_on_files": {
                    "description": "The product name exists on every file bundled with the app",
                    "message": "There are some files that do not refer to the app's name",
                    "success": false,
                    "verbose": [
                        "File `tasks.py` should refer to one of (RFAfP, recordedfuture, recorded future for splunk soar, Recorded Future App for Phantom) in some way"
                    ]
                }
            },
```

If that file indeed doesn't package ignored files I believe this should also be reflected in the static tests. 

cc @bb-splunk @kczernik-splunk @ivellios 

(related to https://github.com/splunk-soar-connectors/recordedfuture/pull/34)

**Comment by bb-splunk** [comment]
Agreed, though in your specific case this file should not have been added as explained in the PR.
